<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Account' => 'Учетная запись',
    'Created At' => 'Дата создания',
    'Email' => '',
    'ID' => '',
    'Last Active At' => 'Последняя активность',
    'Last Login At' => 'Последний раз логинился',
    'Password' => 'Пароль',
    'Password Strategy' => 'Стратегия парольная',
    'Require New Password' => 'Требуется новый пароль',
    'Salt' => 'Соль',
    'Status' => 'Статус',
    'Stay logged in' => 'Запомнить меня',
    'Token' => 'Токен',
    'Type' => 'Тип',
    'Username' => 'Имя пользователя',
    'Verify Password' => 'Подтверждение пароля',
);
