<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Cancel' => 'Отмена',
    'Change Password' => 'Изменить пароль',
    'Create Account' => 'Регистрация',
    'Create an account' => 'Регистрация',
    'Forgot password' => 'Напомнить пароль',
    'If you already have an account &ndash; {loginLink}.' => 'Если у вас уже есть учетная запись &ndash; {loginLink}',
    'Log In' => 'Войти',
    'Please enter a new password twice to change the password for your account.' => 'Пожалуйста введите новый пароль дважды, для установки нового пароля вашего аккаунта',
    'Please enter your email and we will send you instructions on how to recover your account.' => 'Пожалуйста введите свой email и мы вышлем вам инструкцию по восстановлению пароля',
    'Recover Account' => 'Восстановить учетную запись',
    'Thank you for registering!' => 'Спасибо за регистрацию',
    'You have requested a password reset.' => 'Вы запросили сброс пароля.',
    'You will soon receive an email with instructions on how to activate your account.' => 'Вскоре вы получите письмо с инструкциями по активации Вашей учетной записи.',
    'Your password has expired.' => 'Срок действия пароля истек.',
);
