<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => '',
  'Change Password' => '',
  'Create Account' => '',
  'Create an account' => '',
  'Forgot password' => '',
  'If you already have an account &ndash; {loginLink}.' => '',
  'Log In' => '',
  'Please enter a new password twice to change the password for your account.' => '',
  'Please enter your email and we will send you instructions on how to recover your account.' => '',
  'Recover Account' => '',
  'Thank you for registering!' => '',
  'You have requested a password reset.' => '',
  'You will soon receive an email with instructions on how to activate your account.' => '',
  'Your password has expired.' => '',
);
