<?php
/**
 * This file was generated by Caviar.
 * http://github.com/Crisu83/yii-caviar
 */

namespace nordsoftware\yii_account\components;

class TokenGenerator extends \CApplicationComponent
{
    const DEFAULT_TOKEN_LENGTH = 32;

    /**
     * @var int token length.
     */
    public $length = self::DEFAULT_TOKEN_LENGTH;

    /**
     * @var int token strength.
     */
    public $strength = \SecurityLib\Strength::MEDIUM;

    /**
     * @var string characters to use when generating a token string.
     */
    public $chars = '';

    /**
     * @var \RandomLib\Factory RandomLib factory instance.
     */
    private static $_factory;

    /**
     * Generates a new random token.
     *
     * @return string the token
     */
    public function generate()
    {
        $factory = self::getFactory();
        $generator = $factory->getGenerator(new \SecurityLib\Strength($this->strength));
        return $generator->generateString($this->length, $this->chars);
    }

    /**
     * Getter for the RandomLib factory instance.
     *
     * @return \RandomLib\Factory
     */
    protected static function getFactory()
    {
        if (!isset(self::$_factory)) {
            self::$_factory = new \RandomLib\Factory();
        }
        return self::$_factory;
    }
}